FROM python:3.8
EXPOSE 8000
WORKDIR /usr/src/app

# Gerekli dosyaları kopyalayın
COPY ./requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt

COPY ./ ./

# EntryPoint script'ini kopyalayın ve çalıştırılabilir yapın
COPY entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
CMD ["uvicorn", "backend.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "./ssl/key.pem", "--ssl-certfile", "./ssl/cert.pem"]

