# Generated by Django 5.0 on 2023-12-20 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gamerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='game_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='game_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_lose', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='loser_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='score_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='winner_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
